version: '3.8'
services:
  api:
    image: registry.gitlab.com/krishiv-g/steem-full-node-with-api-ah-hivemind
    container_name: STEEM-API
    hostname: api
    command: /usr/local/steemd/bin/steemd --data-dir /var/steem
    volumes:
      - /home/FULL-NODE/API:/var/steem
    ports:
      - "8091:8091"
    networks:
      - steem
    restart: unless-stopped
  
  ah:
    image: registry.gitlab.com/krishiv-g/steem-full-node-with-api-ah-hivemind
    container_name: STEEM-AH
    hostname: ah
    command: /usr/local/steemd/bin/steemd --data-dir /var/steem
    volumes:
      - /home/FULL-NODE/AH:/var/steem
    ports:
      - "8092:8092"
    networks:
      - steem
    restart: unless-stopped

  jussi:
    image: steemit/jussi:latest
    container_name: STEEM-JUSSI
    hostname: jussi
    volumes:
      - /home/FULL-NODE/jussi/config.json:/app/config.json
    environment:
      - JUSSI_UPSTREAM_CONFIG_FILE=/app/config.json
    ports:
      - "8080:8080"
    networks:
      - steem
    stdin_open: true
    tty: true

networks:
  steem:
    external: true